# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61a2edd81ae715b1114a6eefad3654e538e8f43e6a5c48e6ebe511116d067165f86869b908d85bf942f6be17c1fc71053137f4e800f59b9f46db86fda50702a

test:
  secret_key_base: 68160952e7faa01e20b50ddaad9e28c93af2cbe73ad06b2ab2eac43e8da0c0e893b0c584f7e9710e2e4dcc9c2faa673c7dd70283d2dd23f8e7c8baf67a98cbc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
